version: '3.8'

services:
    app:
        build:
            context: .
            args:
                user: dabit
                uid: 1000
        image: laravel-inertia-app
        container_name: laravel-app
        restart: unless-stopped
        environment:
            - APP_URL=http://localhost:9000
            - APP_ENV=production
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=4dayweekjobs
            - DB_USERNAME=root
            - DB_PASSWORD=test
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
            - redis

    db:
        image: mariadb:latest
        container_name: db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=4dayweekjobs
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_PASSWORD=test
            - MYSQL_USER=root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        networks:
            - app-network
        ports:
            - "6379:6379"

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
